apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-custom-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "scc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scc.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: simple-custom-controller-sa
      containers:
        - name: book
          image: {{ .Values.image }}
          imagePullPolicy: Always
