apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scc.fullname" . }}-cluster-role
rules:
  - apiGroups: ["", "apps", "apiextensions.k8s.io"]
    resources: ["pods", "services", "deployments", "configmaps", "customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [ "simplecustomcontroller.crd.com" ]
    resources: [ "books" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "simplecustomcontroller.crd.com" ]
    resources: [ "books/status" ]
    verbs: [ "update" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scc.fullname" . }}-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: simple-custom-controller-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "scc.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io

