apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-custom-controller-cluster-role
rules:
  - apiGroups: ["", "apps", "apiextensions.k8s.io"]
    resources: ["pods", "services", "deployments", "configmaps", "customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [ "simplecustomcontroller.crd.com" ]
    resources: [ "books" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: [ "simplecustomcontroller.crd.com" ]
    resources: [ "books/status" ]
    verbs: [ "update" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch", "update" ]

