apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simple-custom-controller-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: simple-custom-controller-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: simple-custom-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
