apiVersion: simplecustomcontroller.crd.com/v1
kind: Book
metadata:
  name: example-book
spec:
  deploymentName: example-book
  replicas: 1
  container:
    name: book-store
    image: shiponcs/book-store-api-server
    ports:
      - containerPort: 8080

